trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: luoyunchong@foxmail.com            
  namespace: igeekfan                            
  imageName: devops      
  imageNameApi: devops-api      
  registry: registry.cn-hangzhou.aliyuncs.com
  dockerfilepath:  DevOps.Web/Dockerfile 
  dockerfileapipath:  DevOps.Api/Dockerfile 


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo read to execute command
      ls
      sed -i 's/{ConnectionStrings.Default}/$(ConnectionStrings.Default)/g' DevOps.Web/appsettings.Production.json
      echo command executed

- script: |
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker build -f $(dockerfileapipath) -t $(imageNameApi) .
    echo $(pwd) | docker login --username $(dockerId) $(registry) --password-stdin
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)

    docker tag $(imageNameApi) $(registry)/$(namespace)/$(imageNameApi)
    docker push $(registry)/$(namespace)/$(imageNameApi)
  displayName: push to aliyun