version: '3.4'

services:
  devops.api:
    image: ${DOCKER_REGISTRY-}devopsapi
    build:
      context: .
      dockerfile: DevOps.Api/Dockerfile

  devops.web:
    image: ${DOCKER_REGISTRY-}devopsweb
    build:
      context: .
      dockerfile: DevOps.Web/Dockerfile

